### ISSUE TITLE
В задании №21 отсутствует надпись у первой кнопки ответа

### ISSUE THREAD

**Issue by krilena** [kozyul-ka/IQ-TEST#1]
При прохождении теста в задании №21 у первой кнопки ответа отсутствует надпись. Если подразумевалось, что здесь и должен быть пропуск, то лучше бы использовать какой-нибудь символ пропуска, например, "_", а то непонятно

![issue 1](https://user-images.githubusercontent.com/87083280/146196393-75c1f125-9536-4de8-be88-ad6e9aae42ba.jpg)

**Comment by Anastasiya1223** [comment]
Поправки внесены.
