### ISSUE TITLE
В задании №21 некорректное отображение задания

### ISSUE THREAD

**Issue by krilena** [kozyul-ka/IQ-TEST#2]
При прохождении теста в задании №21 некорректно отображается задание. Фактически, там отображается два задания разных сразу: текстом и картинкой - а должно быть что-то одно. Непонятно, какое именно задание необходимо решать.
![issue 1](https://user-images.githubusercontent.com/87083280/146198190-a4bd81c0-a8a0-4a71-8316-697590c08aaf.jpg)

**Comment by Anastasiya1223** [comment]
Поправки внесены.
