### ISSUE TITLE
Отсутствие ограничения на ввод ника приводит к некрасивому отображению очень длинного ника в результатах

### ISSUE THREAD

**Issue by krilena** [kozyul-ka/IQ-TEST#3]
На главной странице, перед началом прохождения теста, если вести слишком длинный ник, то потом, после прохождения теста, в результатах он будет слишком уж некрасиво смотреться. Лучше ограничить фантазию пользователя некоторым ограничением длины вводимого ника)
![Issue 2](https://user-images.githubusercontent.com/87083280/146199769-bec0f1c7-8ef8-4871-b094-837b86c0c5aa.jpg)

**Comment by Anastasiya1223** [comment]
Поправки внесены.
