### ISSUE TITLE
Ошибка при вводе чисел

### ISSUE THREAD

**Issue by Mirayto** [kozyul-ka/IQ-TEST#6]
Задания, где требуется вручную ввести число (11, 12, 15,19, 22, 23 и 24) нет ограничений на ввод числа, программа ломается
![image](https://user-images.githubusercontent.com/96184740/146409832-42854be8-8d44-49c6-aeb4-d49d72a8bf89.png)

**Comment by Anastasiya1223** [comment]
Поправка внесена.
