### ISSUE TITLE
В первом вопросе присутствуют лишние варианты выбора ответа.

### ISSUE THREAD

**Issue by krilena** [kozyul-ka/IQ-TEST#7]
При прохождении теста в первом вопросе присутствуют варианты ответа 5 и 6, хотя фактически их 4.

![image](https://user-images.githubusercontent.com/87083280/146498231-8621c0cd-c9dd-49fc-bcd3-8e2a0d02c4a9.png)

**Comment by Anastasiya1223** [comment]
Issue исправлен.
