### ISSUE TITLE
Ошибка масштабирования в полноэкранном режиме

### ISSUE THREAD

**Issue by krilena** [kozyul-ka/IQ-TEST#8]
При двойном клике на верхнюю область окна проекта оно разворачивается в полноэкранный режим, при этом элементы не скалируются

![image](https://user-images.githubusercontent.com/87083280/146499446-ac6fa75d-eeae-429a-80f7-4224d64b0fb7.png)

**Comment by Anastasiya1223** [comment]
Теперь уж точно нет этого бага!)
